apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - port: 8080
    targetPort: app-port
    protocol: TCP
    nodePort: 30001
  selector:
    app: python-app
  type: NodePort
